[font]
normal = { family = "DejaVuSansM Nerd Font" }
size = 13

[window]
opacity = 1
dimensions = { columns = 100, lines = 30 }

[general]
import = [
  "~/.config/alacritty/themes/solarized_light.toml"
]
